const data = [
  [634, [], ['evens', 'yeesh', 'sleet', 'sweep']],
  [633, [], ['ghast', 'poops', 'surly']],
  [632, [], ['disco', 'plane', 'flame', 'blame']],
  [631, [], ['woops', 'death', 'mirth', 'girth', 'birth']],
  [629, [], ['would', 'later', 'riles', 'repel', 'revel']],
  [628, [], ['maven', 'slice', 'probe', 'there', 'where']],
  [627, [], ['bough', 'angle', 'regal']],
  [626, [], ['bread', 'score', 'horse']],
  [625, [], ['right', 'pines', 'pinny', 'pinky']],
  [624, [], ['cafes', 'block', 'occur', 'tonic', 'topic', 'toxic']],
  [623, [], ['plant', 'trine', 'trend']],
  [622, [], ['crook', 'blame', 'pains', 'assay', 'squad', 'squat']],
  [621, [], ['stoic', 'broke', 'abode', 'above']],
  [618, [], ['delay', 'emote', 'biome', 'moose']],
  [617, [], ['going', 'rowed', 'bouts', 'cooky', 'polka']],
  [616, [], ['robot', 'corgi', 'pored', 'worse']],
  [615, [], ['meter', 'ruins', 'spurt', 'syrup']],
  [614, [], ['boots', 'wrath', 'petty', 'nifty', 'fifty']],
  [613, [], ['shard', 'array', 'arbor']],
  [612, [], ['about', 'malus', 'vague']],
  [611, [], ['tarry', 'error', 'refer', 'rider', 'river', 'riser', 'riper']],
  [610, [], ['whole', 'bunny', 'puffy', 'sucky', 'dummy', 'ruddy']],
  [609, [], ['tacos', 'shone', 'moose', 'gloss', 'dross', 'kiosk']],
  [608, [], ['fully', 'latch', 'altar', 'avail']],
  [607, [], ['algae', 'brave', 'taste', 'cache']],
  [606, [], ['salty', 'dared', 'manic', 'magic']],
  [605, [], ['fiber', 'plant', 'lacks', 'sally', 'salsa']],
  [604, [], ['brink', 'thong', 'mound', 'pound', 'sound']],
  [603, [], ['tummy', 'round', 'laugh', 'usage']],
  [602, [], ['baggy', 'grail', 'giant']],
  [601, [], ['tired', 'deeps', 'death', 'delve', 'defog', 'debug']],
  [600, [], ['tango', 'place', 'deads', 'ready', 'beady', 'heady']],
  [599, [], ['scowl', 'shear', 'sated', 'stage']],
  [598, [], ['elbow', 'glitz', 'plaid', 'flair']],
  [597, [], ['crate', 'abode', 'apple']],
  [596, [], ['wrong', 'sneak', 'punty', 'linty', 'ninth']],
  [595, [], ['cargo', 'batch', 'fancy', 'dance']],
  [594, [], ['scour', 'whump', 'guide', 'unity', 'until', 'unlit']],
  [593, [], ['under', 'chill', 'smoky', 'gassy', 'pasty', 'tasty']],
  [592, [], ['sicks', 'scalp', 'scold']],
  [591, [], ['gulps', 'fares', 'stirs', 'cross']],
  [590, [], ['boxer', 'drive', 'grave', 'crave']],
  [589, [], ['stall', 'guise', 'winos', 'dishy', 'fishy']],
  [588, [], ['worse', 'guard', 'churn', 'flirt']],
  [587, [], ['rifts', 'array', 'lorry', 'worry']],
  [586, [], ['jazzy', 'gurdy', 'whiny', 'peppy', 'felty', 'beefy']],
  [585, [], ['minor', 'mails', 'maize']],
  [584, [], ['proud', 'touts', 'count']],
  [583, [], ['sleep', 'elate', 'elope', 'elude']],
  [582, [], ['bosun', 'grimy', 'meany', 'mazey', 'matey']],
  [581, [], ['float', 'glide', 'plumb', 'blurb']],
  [580, [], ['repel', 'ulcer', 'alter']],
  [578, [], ['brits', 'rodeo', 'chard']],
  [577, [], ['build', 'apode', 'adopt']],
  [576, [], ['maths', 'groin', 'drove', 'frock']],
  [575, [], ['flows', 'sneer', 'spire']],
  [574, [], ['hinge', 'droop', 'vocal', 'loams', 'koala']],
  [573, [], ['kempt', 'lambs', 'woman', 'adman', 'human']],
  [571, [], ['anime', 'eager', 'peats', 'leapt']],
  [570, [], ['scant', 'sneak', 'sedan']],
  [569, [], ['tired', 'piece', 'pixie']],
  [568, [], ['sorry', 'adore', 'opera']],
  [567, [], ['sword', 'ponce', 'ovine', 'melon', 'lemon']],
  [566, [], ['scrat', 'guild', 'libel', 'belie']],
  [565, [], ['awake', 'keeps', 'sleek']],
  [564, [], ['offal', 'layed', 'layer']],
  [563, [], ['clink', 'niche', 'panic', 'antic']],
  [562, [], ['train', 'first', 'shirt', 'skirt']],
  [561, [], ['klutz', 'drive', 'swine', 'whine']],
  [560, [], ['haste', 'valor', 'gaily', 'wally', 'manly']],
  [559, [], ['knave', 'iotas', 'polar', 'molar']],
  [556, [], ['tower', 'dough', 'foods', 'mondo', 'condo']],
  [555, [], ['poops', 'frack', 'delve', 'midge', 'nudge', 'budge', 'judge']],
  [554, [], ['groom', 'chart', 'intra', 'sutra', 'tetra', 'extra']],
  [553, [], ['power', 'podge', 'posse', 'poise']],
  [552, [], ['gouge', 'dorky', 'coral', 'forma', 'sorta', 'porta', 'iorta']],
  [551, [], ['mason', 'fried', 'bevel', 'wheel', 'excel']],
  [550, [], ['hoist', 'crude', 'furry', 'augur', 'lunar']],
  [549, [], ['winch', 'heigh', 'shirk', 'third']],
  [545, [], ['focus', 'avoid', 'growl', 'tromp', 'prone', 'probe']],
  [544, [], ['hotel', 'drill', 'rival']],
  [543, [], ['chomp', 'grade', 'lunas', 'usual']],
  [542, [], ['nerve', 'badge', 'slice', 'smote', 'spoke']],
  [541, [], ['knell', 'scalp', 'apply']],
  [540, [], ['grand', 'lanes', 'eaten', 'naive']],
  [539, [], ['piano', 'donor', 'flown', 'snobs', 'knock']],
  [538, [], ['learn', 'roars', 'fraud', 'braid']],
  [537, [], ['focus', 'after', 'infer']],
  [536, [], ['train', 'emote', 'gothy', 'doubt', 'joust']],
  [535, [], ['dross', 'blurt', 'rebar', 'caber', 'amber']],
  [534, [], ['blink', 'knots', 'wonky', 'woken']],
  [533, [], ['snowy', 'float', 'abode', 'adore']],
  [532, [], ['droop', 'torso']],
  [531, [], ['clogs', 'chart', 'champ', 'chafe']],
  [530, [], ['phage', 'error', 'ennui', 'elect', 'eject']],
  [529, [], ['trash', 'stoop', 'stuck', 'stung', 'stuff', 'studs', 'study']],
  [528, [], ['wreck', 'feint', 'boned', 'nudes', 'undue']],
  [527, [], ['break', 'depth', 'tepid']],
  [526, [], ['chaos', 'alpha', 'happy']],
  [525, [], ['alloy', 'blade', 'pleat', 'clear', 'clean']],
  [524, [], ['faked', 'blows', 'unity', 'pithy', 'itchy']],
  [523, [], ['feast']],
  [522, [], ['lunge', 'chore', 'arise', 'tribe', 'drive']],
  [521, [], ['buggy', 'fixed', 'snipe', 'prize', 'price', 'prime']],
  [520, [], ['couch', 'groan', 'ovals', 'patio', 'axiom']],
  [
    519,
    [
      ['b', 'b', 'b', 'y', 'b'],
      ['b', 'y', 'b', 'b', 'b'],
      ['b', 'g', 'g', 'b', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['today', 'walks', 'crazy', 'brave'],
  ],
  [
    518,
    [
      ['y', 'b', 'y', 'b', 'b'],
      ['b', 'y', 'g', 'b', 'b'],
      ['b', 'b', 'g', 'y', 'y'],
      ['b', 'b', 'g', 'g', 'y'],
      ['g', 'b', 'g', 'g', 'g'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['eerie', 'creed', 'shear', 'opera', 'alert', 'avert'],
  ],
  [
    517,
    [
      ['b', 'b', 'b', 'y', 'b'],
      ['b', 'g', 'b', 'b', 'b'],
      ['b', 'g', 'b', 'b', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['skill', 'blade', 'clout', 'glyph'],
  ],
  [
    516,
    [
      ['b', 'b', 'g', 'b', 'b'],
      ['b', 'b', 'g', 'b', 'g'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['wield', 'scene', 'there'],
  ],
  [
    515,
    [
      ['b', 'y', 'b', 'b', 'y'],
      ['y', 'y', 'b', 'b', 'b'],
      ['b', 'b', 'y', 'g', 'b'],
      ['b', 'g', 'b', 'g', 'g'],
      ['b', 'g', 'b', 'g', 'g'],
      ['b', 'g', 'g', 'g', 'g'],
    ],
    ['froze', 'reels', 'tired', 'waver', 'caper', 'maker', 'baker'],
  ],
  [
    514,
    [
      ['b', 'b', 'b', 'b', 'b'],
      ['b', 'y', 'b', 'y', 'b'],
      ['g', 'b', 'g', 'g', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['bogey', 'crush', 'stark', 'snarl'],
  ],
  [
    513,
    [
      ['g', 'b', 'b', 'b', 'b'],
      ['g', 'b', 'b', 'b', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['month', 'murky', 'maple'],
  ],
  [
    512,
    [
      ['b', 'b', 'b', 'g', 'b'],
      ['b', 'b', 'g', 'g', 'b'],
      ['b', 'y', 'g', 'g', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['brunt', 'plank', 'deans', 'inane'],
  ],
  [
    511,
    [
      ['b', 'b', 'y', 'b', 'b'],
      ['b', 'b', 'y', 'y', 'b'],
      ['b', 'g', 'b', 'y', 'y'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['chain', 'break', 'maple', 'valet'],
  ],
  [
    510,
    [
      ['b', 'g', 'b', 'g', 'b'],
      ['b', 'g', 'g', 'g', 'g'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['vegan', 'pedal', 'medal'],
  ],
  [
    509,
    [
      ['b', 'b', 'b', 'b', 'b'],
      ['b', 'b', 'g', 'b', 'y'],
      ['y', 'b', 'g', 'b', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['color', 'shift', 'taiga', 'unite'],
  ],
  [
    508,
    [
      ['b', 'g', 'b', 'b', 'g'],
      ['b', 'g', 'y', 'b', 'g'],
      ['y', 'g', 'b', 'b', 'g'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['jazzy', 'lanky', 'nappy', 'rainy'],
  ],
  [
    507,
    [
      ['b', 'b', 'b', 'b', 'b'],
      ['b', 'b', 'b', 'b', 'y'],
      ['b', 'b', 'y', 'y', 'y'],
      ['g', 'b', 'g', 'g', 'g'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['frock', 'thine', 'gales', 'swell', 'spell'],
  ],
  [
    506,
    [
      ['g', 'b', 'b', 'b', 'b'],
      ['g', 'y', 'b', 'y', 'b'],
      ['g', 'g', 'y', 'y', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['botch', 'biker', 'beige', 'begin'],
  ],
  [
    505,
    [
      ['b', 'b', 'y', 'y', 'b'],
      ['y', 'b', 'b', 'y', 'y'],
      ['y', 'y', 'g', 'y', 'b'],
      ['g', 'b', 'g', 'g', 'g'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['dream', 'angel', 'leash', 'scale', 'stale'],
  ],
  [
    504,
    [
      ['y', 'b', 'b', 'b', 'b'],
      ['g', 'g', 'y', 'b', 'y'],
      ['g', 'g', 'g', 'g', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['again', 'drape', 'dread', 'dream'],
  ],
  [
    503,
    [
      ['b', 'b', 'g', 'b', 'b'],
      ['b', 'g', 'g', 'b', 'y'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['frown', 'chomp', 'photo'],
  ],
  [
    502,
    [
      ['b', 'b', 'b', 'b', 'b'],
      ['b', 'b', 'g', 'b', 'y'],
      ['b', 'g', 'g', 'b', 'b'],
      ['b', 'g', 'g', 'b', 'g'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['knife', 'growl', 'sloth', 'blood', 'aloud'],
  ],
  [
    501,
    [
      ['b', 'y', 'b', 'b', 'y'],
      ['y', 'b', 'b', 'y', 'g'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['spoon', 'plant', 'inept'],
  ],
  [
    500,
    [
      ['b', 'y', 'y', 'b', 'b'],
      ['y', 'g', 'b', 'b', 'b'],
      ['g', 'g', 'g', 'b', 'b'],
      ['g', 'g', 'g', 'g', 'b'],
      ['g', 'g', 'g', 'g', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['onion', 'night', 'pinch', 'pined', 'pines', 'piney'],
  ],
  [
    499,
    [
      ['b', 'y', 'y', 'b', 'b'],
      ['y', 'b', 'b', 'b', 'g'],
      ['b', 'g', 'b', 'b', 'g'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['hyped', 'porky', 'spicy', 'aptly'],
  ],
  [
    498,
    [
      ['b', 'b', 'b', 'b', 'b'],
      ['y', 'g', 'b', 'b', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['every', 'laugh', 'waltz'],
  ],
  [
    497,
    [
      ['b', 'g', 'b', 'b', 'b'],
      ['b', 'g', 'b', 'b', 'y'],
      ['b', 'g', 'b', 'g', 'b'],
      ['b', 'g', 'y', 'g', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['fight', 'diode', 'riven', 'piles', 'libel'],
  ],
  [
    496,
    [
      ['b', 'b', 'y', 'y', 'b'],
      ['g', 'y', 'b', 'y', 'b'],
      ['g', 'y', 'b', 'g', 'y'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['crash', 'sauna', 'sedan', 'sneak'],
  ],
  [
    495,
    [
      ['b', 'b', 'b', 'g', 'b'],
      ['b', 'b', 'y', 'g', 'b'],
      ['b', 'g', 'b', 'g', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['storm', 'quark', 'faire', 'carry'],
  ],
  [
    494,
    [
      ['b', 'b', 'b', 'b', 'y'],
      ['g', 'y', 'y', 'b', 'b'],
      ['g', 'g', 'g', 'b', 'b'],
      ['g', 'g', 'g', 'b', 'b'],
      ['g', 'g', 'g', 'b', 'g'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['grief', 'folds', 'flown', 'flock', 'float', 'flout'],
  ],
  [
    493,
    [
      ['b', 'b', 'y', 'b', 'b'],
      ['b', 'g', 'b', 'b', 'b'],
      ['b', 'g', 'b', 'b', 'b'],
      ['b', 'g', 'g', 'g', 'g'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['cloth', 'roads', 'women', 'boggy', 'foggy'],
  ],
  [
    492,
    [
      ['b', 'b', 'b', 'b', 'b'],
      ['b', 'y', 'b', 'g', 'g'],
      ['y', 'b', 'g', 'g', 'g'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['porch', 'built', 'adult', 'fault'],
  ],
  [
    491,
    [
      ['b', 'b', 'b', 'b', 'b'],
      ['b', 'g', 'b', 'b', 'b'],
      ['b', 'g', 'b', 'b', 'b'],
      ['b', 'g', 'g', 'b', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['spank', 'butte', 'guild', 'humor', 'mummy'],
  ],
  [
    490,
    [
      ['y', 'b', 'b', 'g', 'b'],
      ['b', 'b', 'b', 'g', 'g'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['later', 'dowel', 'spiel'],
  ],
  [
    489,
    [
      ['b', 'b', 'b', 'b', 'b'],
      ['b', 'b', 'g', 'b', 'b'],
      ['b', 'g', 'g', 'b', 'g'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['fluff', 'adopt', 'crone', 'grove'],
  ],
  [
    488,
    [
      ['b', 'b', 'b', 'y', 'b'],
      ['y', 'b', 'y', 'b', 'y'],
      ['b', 'y', 'g', 'y', 'y'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['haunt', 'noise', 'pined', 'denim'],
  ],
  [
    487,
    [
      ['b', 'b', 'b', 'b', 'b'],
      ['b', 'b', 'b', 'b', 'b'],
      ['b', 'b', 'y', 'b', 'b'],
      ['y', 'y', 'b', 'b', 'b'],
      ['b', 'y', 'g', 'b', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['allay', 'tooth', 'verve', 'rigid', 'primp', 'quirk'],
  ],
  [
    486,
    [
      ['b', 'b', 'b', 'b', 'b'],
      ['b', 'b', 'y', 'b', 'b'],
      ['y', 'y', 'b', 'y', 'b'],
      ['b', 'y', 'b', 'y', 'y'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['foggy', 'quell', 'strep', 'dents', 'exist'],
  ],
  [
    485,
    [
      ['b', 'b', 'y', 'y', 'b'],
      ['b', 'y', 'y', 'y', 'y'],
      ['g', 'b', 'g', 'g', 'g'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['doing', 'fines', 'skein', 'stein'],
  ],
  [
    484,
    [
      ['y', 'b', 'b', 'b', 'b'],
      ['b', 'b', 'b', 'g', 'y'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['ditzy', 'words', 'spade'],
  ],
  [
    483,
    [
      ['b', 'b', 'b', 'b', 'b'],
      ['b', 'b', 'b', 'b', 'b'],
      ['g', 'b', 'b', 'b', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['gorge', 'sunny', 'cliff', 'catch'],
  ],
  [
    482,
    [
      ['b', 'y', 'b', 'b', 'b'],
      ['y', 'b', 'b', 'y', 'b'],
      ['b', 'y', 'g', 'b', 'b'],
      ['y', 'b', 'g', 'b', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['mound', 'ovary', 'grope', 'riots', 'floor'],
  ],
  [
    480,
    [
      ['y', 'b', 'b', 'b', 'b'],
      ['b', 'b', 'b', 'y', 'b'],
      ['b', 'y', 'b', 'g', 'g'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['clued', 'aback', 'mimic', 'ionic'],
  ],
  [
    479,
    [
      ['b', 'y', 'b', 'b', 'b'],
      ['b', 'g', 'g', 'b', 'b'],
      ['y', 'g', 'g', 'b', 'b'],
      ['g', 'g', 'g', 'g', 'g'],
    ],
    ['clots', 'ralph', 'dally', 'valid'],
  ],
];
